-- CreateTable
CREATE TABLE "venues" (
    "accomondation" TEXT,
    "address" TEXT,
    "area" TEXT,
    "autodetected" TEXT,
    "bookatable_clientid" TEXT,
    "bookatable_partnerCode" TEXT,
    "bookingnotes" TEXT,
    "businessId" TEXT,
    "businessid" TEXT,
    "city" TEXT,
    "close" BOOLEAN,
    "closehours" TEXT,
    "connectionid" TEXT,
    "country" TEXT,
    "countryISO" TEXT,
    "coverImage" TEXT,
    "creationTime" TEXT,
    "cuisine" TEXT,
    "currency" TEXT,
    "devnotes" TEXT,
    "distinction" TEXT,
    "email" TEXT,
    "fulladdress" TEXT,
    "guide" TEXT,
    "imageList" TEXT,
    "key" TEXT NOT NULL,
    "latitude" DOUBLE PRECISION,
    "localarea" TEXT,
    "localname" TEXT,
    "longitude" DOUBLE PRECISION,
    "menuurl" TEXT,
    "metro" TEXT,
    "michelinId" TEXT,
    "michelineOnlineReservation" BOOLEAN,
    "name" TEXT,
    "oldImages" TEXT,
    "openhours" TEXT,
    "otherReservation" TEXT,
    "phone" TEXT,
    "priceline" TEXT,
    "realurl" TEXT,
    "region" TEXT,
    "reservation" TEXT,
    "reservationHint" TEXT,
    "reservationUrl" TEXT,
    "resy_city_code" TEXT,
    "resy_url_slug" TEXT,
    "rsvp_support" TEXT,
    "sf" TEXT,
    "showvenue" BOOLEAN,
    "stars" TEXT,
    "tags" TEXT,
    "timezone" TEXT,
    "tock_url_slug" TEXT,
    "url" TEXT,
    "url_slug" TEXT,
    "withOnlineReservation" TEXT,
    "workqueue" TEXT,
    "zip" TEXT,
    "vintage" TEXT,
    "street_usps" TEXT,

    CONSTRAINT "venues_pkey" PRIMARY KEY ("key")
);
